
version: '3.8'

services:
  # Frontend React application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - db
    networks:
      - artify-network
    restart: unless-stopped


  # Supabase database container
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - artify-network
    restart: unless-stopped

networks:
  artify-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
