
version: '3.8'

services:
  # Frontend React application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - db
    networks:
      - artify-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Supabase database container
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - artify-network
    restart: unless-stopped

  # Test environment service (optional - for local testing)
  selenium-tests:
    image: markhobson/maven-chrome:jdk-11
    volumes:
      - ./tests:/workspace
    working_dir: /workspace
    networks:
      - artify-network
    command: mvn clean test
    depends_on:
      - app
    profiles:
      - testing

networks:
  artify-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
